config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'static_pages#top'
  get '/index.html', to: 'static_pages#top'
  get '/privacy_policy', to: 'static_pages#privacy_policy'
  get '/term_of_use', to: 'static_pages#term_of_use'
  get '/guide', to: 'static_pages#guide'
  get :sign_up, to: 'users#new'
  post :sign_up, to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  post '/guest_login', to: 'guest_sessions#create'
  delete '/guest_logout', to: 'guest_sessions#destroy'
  post '/callback', to: 'line_bot#callback'
  get '/callback', to: 'oauths#callback'
  post 'oauth/callback', to: 'oauths#callback'
  get 'oauth/:provider', to: 'oauths#oauth', as: :auth_at_provider
  resources :items do
    collection do
      get 'search'
      get 'already_expired'
    end
    patch 'increment', on: :member
    patch 'decrement', on: :member
  end
  resources :users, only: %i[new create destroy]
  resource :authentication
  resource :profile, only: %i[show edit update]
  resources :shopping_lists, only: %i[index create new edit update]
  delete 'shopping_lists/destroy', to: 'shopping_lists#destroy_selected', as: :destroy_selected_shopping_lists
  resources :password_resets, only: %i[new create edit update]
  resources :inquiries, only: %i[new create] do
    get '/mentions', to: 'inquiries#mentions'
  end

  namespace :admin do
    root to: 'dashboards#index'
    get '/login', to: 'user_sessions#new'
    post '/login', to: 'user_sessions#create'
    delete '/logout', to: 'user_sessions#destroy'
    resources :users, only: %i[index edit update show destroy] do
      collection do
        get 'search'
      end
    end

    resources :items, only: %i[index edit update show destroy] do
      collection do
        get 'search'
      end
    end

    resources :shopping_lists, only: %i[index update show destroy] do
      collection do
        get 'search'
      end
    end
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/views/shared/_error_message.html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger">
    <ul class="mb-0 list-unstyled">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger">
    <ul class="mb-0 list-unstyled">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer-info">
    <ul>
      <li class="nav-item">
        <%= link_to t('defaults.inquiry'), new_inquiry_path, class: "link" %>
      </li>
      <li class="nav-item">
        <%= link_to t('defaults.term_of_use'), term_of_use_path, class: "link" %>
      </li>
      <li class="nav-item">
        <%= link_to t('defaults.privacy_policy'), privacy_policy_path, class: "link" %>
      </li>
      <li class="nav-item">
        <%= link_to t('defaults.guide'), guide_path, class: "link" %>
      </li>
    </ul>
  <p class="copyright">© 2023 this is created by expired-foods</p>
</div>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">expired foods</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        <% if current_user.present? %>
          <li class="nav-item">
            <%= link_to t('defaults.register_item'), new_item_path, class: 'nav-link'%>
          </li>
          <li class="nav-item">
            <%= link_to t('defaults.item_list'), items_path, class: 'nav-link'%>
          </li>
           <li class="nav-item">
            <%= link_to t('defaults.shopping_list'), shopping_lists_path, class: 'nav-link' %>
          </li>
           <% if current_user.email != 'guestuser@example.com' %>
            <li class="nav-item">
              <%= link_to t('defaults.setting'), profile_path, class: 'nav-link' %>
            </li>
           <% end %>
            <li class="nav-item">
              <%= link_to t('defaults.logout'), logout_path, class: 'nav-link', method: :delete, data: { confirm: 'ログアウトしますか？' } %>
            </li>
        <% else %>
          <li class="nav-item">
            <%= link_to t('defaults.enroll'), sign_up_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to t('defaults.login'), login_path, class: 'nav-link' %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>