config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'static_pages#top'
  get '/index.html', to: 'static_pages#top'
  get '/privacy_policy', to: 'static_pages#privacy_policy'
  get '/term_of_use', to: 'static_pages#term_of_use'
  get '/guide', to: 'static_pages#guide'
  get :sign_up, to: 'users#new'
  post :sign_up, to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  post '/guest_login', to: 'guest_sessions#create'
  delete '/guest_logout', to: 'guest_sessions#destroy'
  post '/callback', to: 'line_bot#callback'
  get '/callback', to: 'oauths#callback'
  post 'oauth/callback', to: 'oauths#callback'
  get 'oauth/:provider', to: 'oauths#oauth', as: :auth_at_provider
  resources :items do
    collection do
      get 'search'
      get 'already_expired'
    end
    patch 'increment', on: :member
    patch 'decrement', on: :member
  end
  resources :users, only: %i[new create destroy]
  resource :authentication
  resource :profile, only: %i[show edit update]
  resources :shopping_lists, only: %i[index create new edit update]
  delete 'shopping_lists/destroy', to: 'shopping_lists#destroy_selected', as: :destroy_selected_shopping_lists
  resources :password_resets, only: %i[new create edit update]
  resources :inquiries, only: %i[new create] do
    get '/mentions', to: 'inquiries#mentions'
  end

  namespace :admin do
    root to: 'dashboards#index'
    get '/login', to: 'user_sessions#new'
    post '/login', to: 'user_sessions#create'
    delete '/logout', to: 'user_sessions#destroy'
    resources :users, only: %i[index edit update show destroy] do
      collection do
        get 'search'
      end
    end

    resources :items, only: %i[index edit update show destroy] do
      collection do
        get 'search'
      end
    end

    resources :shopping_lists, only: %i[index update show destroy] do
      collection do
        get 'search'
      end
    end
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :count, presence: true, numericality: true
  validates :expired_at, presence: true
  validates :detail, length: { minimum: 0, maximum: 256 }

  validate :check_guest_user_limit, if:-> { user&.guest? }

  scope :latest_expired, -> { where('expired_at > ?', Time.now).order(expired_at: :desc) }
  scope :close_expired, -> { where('expired_at > ?', Time.now).order(expired_at: :asc) }
  scope :already_expired, -> { where('expired_at <= ?', Time.current) }
  scope :search_title, ->(title) { where("title LIKE :word", word: "%#{title}%") }
  scope :search_detail, ->(detail) { where("detail LIKE :word", word: "%#{detail}%") }
  scope :search_user_id_item, ->(user_id_item) { where("user_id LIKE :word", word: "%#{user_id_item}%") }

  def remaining_days
    today = Date.today
    expired_date = expired_at.to_date

    if expired_date == today
      '期限当日です'
    elsif expired_date < today
      '期限切れです'
    else
      remaining_days = (expired_date - today).to_i
      "#{remaining_days}日"
    end
  end

  def check_guest_user_limit
    if user.guest? && user.items.count >= 3
      errors.add(:base, 'ゲストユーザーは3つまでしかアイテムを登録できません。')
    end
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < Admin::BaseController
  before_action :set_item, only: %i[edit update show destroy]

  def index
    @items = Item.all.order(created_at: :desc).page(params[:page])
  end

  def edit; end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item), success: t('.message_item_update')
    else
      flash.now['danger'] = t('.not_to_update')
      render :edit
    end
  end

  def show; end

  def destroy
    @item.destroy!
    redirect_to admin_item_path, success: t('.message_deleted')
  end

  def search
    @search_items_form = SearchItemsForm.new(search_item_params)
    @search_items = @search_items_form.search.order(created_at: :desc).page(params[:page]).per(20)
  end

  private

  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:title, :count, :expired_at, :image, :image_cache, :detail)
  end

  def search_item_params
    params.fetch(:q, {}).permit(:title, :detail)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[edit update destroy increment decrement]

  def index
    @items = item_sort(params)
  end

  def already_expired
    @expired_items = current_user.items.already_expired.order(created_at: :desc).page(params[:page]).per(10)
  end

  def new
    @item = Item.new
  end

  def create
    @item = current_user.items.build(item_params)
    if @item.save
      redirect_to items_path, success: t('.message_create')
    else
      render :new, danger: t('.not_to_create')
    end
  end

  def edit; end

  def update
    if @item.update(item_params)
      redirect_to items_path, success: t('.message_item_update')
    else
      render :edit, danger: t('.not_to_update')
    end
  end

  def destroy
    @item.destroy!
    redirect_to items_path, success: t('.message_deleted')
  end

  def search
    @search_items_form = SearchItemsForm.new(search_item_params) # form_objectを使用してsearchする
    @search_items = @search_items_form.search.order(created_at: :desc).page(params[:page]).per(5)
  end

  def increment
    @item.increment!(:count)
    redirect_to items_path, success: t('.increase')
  end

  def decrement
    if @item.count > 0 # 0以下にならないようにする @item.count.positive?
      @item.decrement!(:count)
      redirect_to items_path, warning: t('.decrease')
    else
      redirect_to items_path, warning: t('.not_exceed_zero')
    end
  end

  private

  def set_item
    @item = current_user.items.find(params[:id])
  end

  def item_sort(params)
    if params[:latest_expired] # 賞味期限が遠い順
      current_user.items.latest_expired.page(params[:page]).per(10)
    elsif params[:close_expired] # 賞味期限が遠い順
      current_user.items.close_expired.page(params[:page]).per(10)
    else
      current_user.items.close_expired.order(created_at: :desc).page(params[:page]).per(10)
    end
  end

  def item_params
    params.require(:item).permit(:title, :count, :expired_at, :detail)
  end

  def search_item_params
    params.fetch(:q, {}).permit(:title, :detail)
  end
end

app/views/items/_crud_menus.html.erb
<%= link_to edit_item_path(item), class: "line-center", id: "button-edit-#{item.id}" do %>
  <%= icon 'fa', 'pen' %>
<% end %>
 |
<%= link_to item_path(item), class: "line-center", id: "button-delete-#{item.id}", method: :delete, data:{confirm: t('defaults.message.deleted_confirm')} do %>
  <%= icon 'fas', 'eraser' %>
<% end %>

app/views/items/_form.html.erb
<%= form_with model: item, local: true do |f| %>
 <%= render 'shared/error_messages', object: f.object %>
  <%= f.select :template, options_for_select(["テンプレート(クリックすると選択できます)", "牛肉", "刺身", "鮭", "卵"]), {}, id: 'item_template' %>
    <%= link_to t('defaults.use_template'), 'javascript:void(0);', id: 'use_template_button', class: 'btn btn-outline-primary' %>
  <div class="mb-3 required-field">
    <%= f.label :title %><span class="required-icon"></span>
    <%= f.text_field :title, id: 'item_title', class: 'form-control' %>
  </div>
  <div class="form-group required-field">
    <%= f.label :count %><span class="required-icon"></span>
    <%= f.number_field :count, min: 1, class: 'form-control' %>
  </div>
  <div class="mb-3 required-field">
    <%= f.label :expired_at %><span class="required-icon"></span>
    <%= f.date_field :expired_at, class: 'form-control' %>
  </div>
  <div class="mb-3">
    <%= f.text_field :detail, placeholder: 'メモ(買った場所や値段、量などの情報を入力しましょう)', class: 'textarea-memo' %>
  </div>
  <%= f.submit t('defaults.register'), class: 'btn btn-primary' %>
<% end %>

 

app/views/items/_item.html.erb
<% if current_user&.mine?(item) %>
 <li id="<%= dom_id(item) %>">
  <div class="card">
    <div class="card-body">
      <div class="item-info"><%= link_to item.title, "#", class: 'item-modal-trigger', data: { toggle: 'modal', target: "#itemModal#{item.id}" }%></div>
      <div class="item-info">
       <%= button_to '+', increment_item_path(item), method: :patch, class: 'btn btn-primary item-action', data: { action: 'increment' } %>
        数:<%= item.count %>
       <%= button_to '-', decrement_item_path(item), method: :patch, class: 'btn btn-danger item-action', data: { action: 'decrease' } %>
      </div>
      <div class="item-info"><%= icon 'fa', 'calendar-days'%><%= item.expired_at.strftime('%Y-%m-%d') %></div>
      <div class="item-info"><%= icon 'fas', 'clock'%><%= item.remaining_days %></div>
      <div class="item-info"><%= render 'crud_menus', { item: item } %></div>
    </div>
  </div>
 </li>
<% end %>

<div class="modal fade" id="itemModal<%= item.id %>" tabindex="-1" role="dialog" aria-labelledby="itemModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="itemModalLabel"><%= item.title %>の詳細</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
       <div class='row'>
           <div class='col-md-12'>
             <h3 class="d-inline"><%= item.title %></h3>
             <ul class="list-inline">
                 <li class="list-inline-item"><%= t('defaults.count')%>:<%= item.count %>個</li>
                 <li class="list-inline-item"><%= icon 'fa', 'calendar-days'%><%= item.expired_at.strftime('%Y-%m-%d') %></li>
                 <li class="list-inline-item"><%= item.remaining_days %></li>
                 <div class="box3"><%= item.detail %></div>
             </ul>
               <%= link_to '冷蔵庫の中身に戻る', items_path, class: 'btn btn-secondary' %>
           </div>
         </div>
      </div>
    </div>
  </div>
</div>

app/views/items/_search_form_items.html.erb
<%= form_with model: @search_items_form, scope: :q, url: search_items_path, class: "d-flex", method: :get do |f| %>
  <%= f.search_field :title, id: "search_field_of_item", class: "form-control me-2", placeholder: "商品名" %>
  <%= button_tag type: "submit", class: "btn btn-default" do %>
    <i class="fa-brands fa-sistrix"></i>
  <% end %>
<% end %>

app/views/items/_search_items.html.erb
<li id="<%= dom_id(item) %>">
  <div class="card">
    <div class="card-body">
      <div class="item-info"><%= search_item.title %></div>
      <div class="item-info">数:<%= search_item.count %></div>
      <div class="item-info">期限:<%= search_item.expired_at.strftime('%Y-%m-%d') %></div>
      <div class="item-info"><%= search_item.remaining_days %></div>
      <div class="item-info"><%= search_item.detail %>
      <div class="item-info"><%= render 'crud_menus', { item: item } %></div>
    </div>
  </div>
  <hr>
</li>

app/views/items/already_expired.html.erb
<% content_for(:title, t('.title')) %>
  <div class="item-box">
    <div class="box-header">
       <%= render 'search_form_items' %>
      <h3 class="box-title"><% t('.title')%></h3>
      <div class="ul list-inline">
        <li>
          <label for="item-sort"><i class="fa-solid fa-filter"></i></label>
            <select id="item-sort-select">
              <option value="expired"><%= t('.expiration')%></option>
            </select>
          <%= link_to t('.all_items'), items_path, class: 'btn btn-outline-primary' %>
        </li>
      </div>
    </div>
      <% if @expired_items.present? %>
        <%= render @expired_items %>
      <% else %>
        <p><%= t('.nothing')%></p>
      <% end %>
      <%= paginate @expired_items, theme: 'bootstrap-5' %>
  </div>

app/views/items/edit.html.erb
<% content_for(:title, @item.title) %>
<div class="content">
  <div class="row">
    <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2">
      <div class="card-label">
        <div class="card-header">
          <i class="bi bi-calendar me-2"></i>
          <span><%= t('.item_edit')%></span>
        </div>
        <div class="box2">
          <%= render 'form', { item: @item } %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/items/index.html.erb
<% content_for(:title, t('.title')) %>
  <div class="item-box">
    <div class="box-header">
       <%= render 'search_form_items' %>
      <h3 class="box-title"><% t('.title')%></h3>
      <div class="ul list-inline">
        <li>
          <label for="item-sort"><i class="fa-solid fa-filter"></i></label>
            <select id="item-sort-select">
              <option value="default"><%= t('.sort')%></option>
              <option value="latest"><%= t('.latest_expired_at')%></option>
              <option value="close"><%= t('.oldest_expired_at')%></option>
            </select>
          <%= link_to t('.expiration'), already_expired_items_path, class: 'btn btn-outline-dark' %>
        </li>
      </div>
    </div>
      <% if @items.present? %>
        <%= render @items %>
      <% else %>
        <p><%= t('.nothing')%></p>
      <% end %>
      <%= paginate @items, theme: 'bootstrap-5' %>
  </div>

app/views/items/new.html.erb
<% content_for(:title, t('.title')) %>
<div class="content">
  <div class="row">
    <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2">
      <div class="card-label">
        <div class="card-header">
          <i class="bi bi-calendar me-2"></i>
          <span><%= t('.register_item')%></span>
        </div>
        <div class="box2">
          <%= render 'form', { item: @item } %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/items/search.html.erb
<% content_for(:title, t('.title')) %>
  <div class="item-box">
    <div class="box-header">
       <%= render 'search_form_items' %>
      <h3 class="box-title"><% t('.title')%></h3>
      <div class="ul list-inline">
        <li>
          <label for="item-sort"><%= t('.expired_at')%></label>
            <select id="item-sort-select">
              <option value="default"><%= t('.sort')%></option>
              <option value="latest"><%= t('.latest_expired_at')%></option>
              <option value="expired"><%= t('.oldest_expired_at')%></option>
            </select>
        </li>
      </div>
    </div>
      <% if @search_items.present? %>
        <%= render @search_items %>
      <% else %>
        <p><%= t('.nothing')%></p>
      <% end %>
      <%= paginate @search_items, theme: 'bootstrap-5' %>
  </div>