config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'static_pages#top'
  get '/index.html', to: 'static_pages#top'
  get '/privacy_policy', to: 'static_pages#privacy_policy'
  get '/term_of_use', to: 'static_pages#term_of_use'
  get '/guide', to: 'static_pages#guide'
  get :sign_up, to: 'users#new'
  post :sign_up, to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  post '/guest_login', to: 'guest_sessions#create'
  delete '/guest_logout', to: 'guest_sessions#destroy'
  post '/callback', to: 'line_bot#callback'
  get '/callback', to: 'oauths#callback'
  post 'oauth/callback', to: 'oauths#callback'
  get 'oauth/:provider', to: 'oauths#oauth', as: :auth_at_provider
  resources :items do
    collection do
      get 'search'
      get 'already_expired'
    end
    patch 'increment', on: :member
    patch 'decrement', on: :member
  end
  resources :users, only: %i[new create destroy]
  resource :authentication
  resource :profile, only: %i[show edit update]
  resources :shopping_lists, only: %i[index create new edit update]
  delete 'shopping_lists/destroy', to: 'shopping_lists#destroy_selected', as: :destroy_selected_shopping_lists
  resources :password_resets, only: %i[new create edit update]
  resources :inquiries, only: %i[new create] do
    get '/mentions', to: 'inquiries#mentions'
  end

  namespace :admin do
    root to: 'dashboards#index'
    get '/login', to: 'user_sessions#new'
    post '/login', to: 'user_sessions#create'
    delete '/logout', to: 'user_sessions#destroy'
    resources :users, only: %i[index edit update show destroy] do
      collection do
        get 'search'
      end
    end

    resources :items, only: %i[index edit update show destroy] do
      collection do
        get 'search'
      end
    end

    resources :shopping_lists, only: %i[index update show destroy] do
      collection do
        get 'search'
      end
    end
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  has_many :items, dependent: :destroy
  has_many :shopping_lists, dependent: :destroy
  has_many :authentications, dependent: :destroy
  accepts_nested_attributes_for :authentications

  validates :name, uniqueness: true, presence: true, length: { maximum: 25 }
  validates :email, uniqueness: true, presence: true
  validates :password, presence: true, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :reset_password_token, uniqueness: true, allow_nil: true

  enum role: { general: 0, admin: 1 }

  scope :search_user_name, ->(name) { where("name LIKE :word", word: "%#{name}%") }
  scope :search_email, ->(email) { where("email LIKE :word", word: "%#{email}%") }

  validate :cannot_change_email, on: :update, if: -> { guest? && email_changed? }

  def cannot_change_email
    errors.add(:email, 'ゲストユーザーのemailは変更できません。')
  end

  def mine?(object)
    id == object.user_id
  end

  def guest?
    email == 'guestuser@example.com'
  end

  def self.guest
    find_or_initialize_by(email: 'guestuser@example.com') do |user|
      user.name = 'guest' if user.new_record?
      user.password = SecureRandom.hex(10) if user.new_record?
      user.password_confirmation = user.password if user.new_record?
      user.role = :general
      user.save! if user.new_record?
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_action :set_user, only: %i[edit update show destroy]

  def index
    @users = User.all.order(created_at: :desc).page(params[:page])
  end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to admin_user_path(@user), success: t('defaults.message.updated', item: User.model_name.human)
    else
      flash.now[:danger] = t('.fail')
      render :edit
    end
  end

  def show; end

  def destroy
    @user.destroy!
    redirect_to admin_users_path, success: t('defaults.message.deleted', item: User.model_name.human)
  end

  def search
    @search_users_form = SearchUsersForm.new(search_email_params)
    @search_users = @search_users_form.search.order(created_at: :desc).page(params[:page]).per(20)
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :role)
  end

  def search_email_params
    params.fetch(:q, {}).permit(:user, :email)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: %i[new create update destroy]
  before_action :set_user, only: %i[edit update]

  def new
    @sign_up_form = SignUpForm.new
  end

  def create
    @sign_up_form = SignUpForm.new(sign_up_form_params) #form_objectを使用してユーザー登録
    if @sign_up_form.save
      redirect_to login_path, success: t('.success')
    else
      flash.now[:danger] = t('.fail')
      render :new
    end
  end

  def show
    set_current_user
    @authentication = current_user.authentications.find_by(provider: 'line')
  end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user.id), success: t('.success')
    else
      render :edit, danger: t('.not_to_update')
    end
  end

  def destroy
    @user = User.find_by(id: params[:id])
    @user.destroy!
    redirect_to root_path, success: t('.success')
  end

  private

  def sign_up_form_params
    params.require(:sign_up_form).permit(:name, :email, :password, :password_confirmation)
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :reset_password_token, :uid)
  end

  def set_user
    @user = User.find(id: params[:id])
  end

  def set_current_user
    @current_user = User.find(current_user.id)
  end
end

app/views/admin/users/_search_form_users.html.erb
<%= form_with model: @search_users_form, scope: :q, url: search_admin_users_path, method: :get, local: true do |f| %>
  <%= f.search_field :name, class: "form-control me-2", placeholder: "ユーザー名" %>
  <%= f.search_field :email, class: "form-control me-2", placeholder: "メールアドレス" %>
  <%= f.submit '検索', class: 'btn btn-outline-primary' %>
<% end %>

app/views/admin/users/_search_users.html.erb
<tr>
  <td>
    <%= search_user.id %>
  </td>
  <td>
    <%= search_user.email %>
  </td>
  <td>
    <%= search_user.role_i18n %>
  </td>
  <td>
    <%= l search_user.created_at, format: :long %>
  </td>
  <td>
    <%= link_to t('defaults.show'), admin_user_path(user), class: 'btn btn-info' %>
    <%= link_to t('defaults.edit'), edit_admin_user_path(user), class: 'btn btn-success' %>
    <%= link_to t('defaults.delete'), admin_user_path(user), method: :delete, data: { confirm: t('defaults.message.deleted_confirm') }, class: 'btn btn-danger' %>
  </td>
</tr>

app/views/admin/users/_user.html.erb
<tr>
  <td>
    <%= user.id %>
  </td>
  <td>
    <%= user.name %>
  </td>
  <td>
    <%= user.email %>
  </td>
  <td>
    <%= user.role_i18n %>
  </td>
  <td>
    <%= l user.created_at, format: :long %>
  </td>
  <td>
    <% if user.uid.present?%>
     <p>LINEに連携済み</p>
    <% else %>
     <p>LINEに連携していません</p>
    <% end %>
  </td>
  <td>
    <%= link_to t('defaults.show'), admin_user_path(user), class: 'btn btn-info' %>
    <%= link_to t('defaults.edit'), edit_admin_user_path(user), class: 'btn btn-success' %>
    <%= link_to t('defaults.delete'), admin_user_path(user), method: :delete, data: { confirm: t('defaults.message.deleted_confirm') }, class: 'btn btn-danger' %>
  </td>
</tr>

app/views/admin/users/edit.html.erb
<div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2">
  <h1><%= t ('.title') %></h1>
    <%= form_with model: @user, url: admin_user_path(@user), local: true do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
        <div class="form-group">
          <%= f.label :email %>
          <%= f.email_field :email, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :role %>
          <%= f.select :role, User.roles_i18n.invert, {}, class: 'form-control' %>
        </div>
        <%= f.submit class: 'btn btn-primary' %>
    <% end %>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<% content_for(:title, t('.title')) %>
<div class="container mb-5 pt-2">
  <h1><%= t('.title') %></h1>
  <div class="row">
    <div class="col-md-12 mb-3">
     <%= render 'search_form_users' %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <table class="table table-striped">
        <thead>
        <tr>
          <th scope="col"><%= User.human_attribute_name(:id) %></th>
          <th scope="col"><%= User.human_attribute_name(:name) %></th>
          <th scope="col"><%= User.human_attribute_name(:email) %></th>
          <th scope="col"><%= User.human_attribute_name(:role) %></th>
          <th scope="col"><%= User.human_attribute_name(:created_at) %></th>
          <th scope="col"><%= User.human_attribute_name(:uid) %></th>
        </tr>
        </thead>
        <tbody>
        <%= render @users %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <!-- ページネーション -->
      <%= paginate @users %>
    </div>
  </div>
</div>

app/views/admin/users/search.html.erb
<% content_for(:title, t('.title')) %>
<div class="container mb-5 pt-2">
  <h1><%= t('.title') %></h1>
  <div class="row">
    <div class="col-md-12 mb-3">
     <%= render 'search_form_users'%>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <table class="table table-striped">
        <thead>
        <tr>
          <th scope="col"><%= User.human_attribute_name(:id) %></th>
          <th scope="col"><%= User.human_attribute_name(:email) %></th>
          <th scope="col"><%= User.human_attribute_name(:role) %></th>
          <th scope="col"><%= User.human_attribute_name(:created_at) %></th>
          <th scope="col"></th>
        </tr>
        </thead>
        <tbody>
        <%= render @search_users %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <!-- ページネーション -->
      <%= paginate @search_users %>
    </div>
  </div>
</div>

app/views/admin/users/show.html.erb
<% content_for(:title, @user.email) %>
<div class="container">
  <div class="row">
    <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2">
      <h1><%= t('.title') %></h1>
      <div class="text-right mb-3">
        <%= link_to t('defaults.edit'), edit_admin_user_path(@user), class: 'btn btn-success' %>
        <%= link_to t('defaults.delete'), admin_user_path(@user), method: :delete, data: { confirm: t('defaults.message.deleted_confirm') }, class: 'btn btn-danger' %>
      </div>
      <table class="table table-bordered bg-white">
        <tr>
          <th scope="row"><%= User.human_attribute_name(:id) %></th>
          <td><%= @user.id %></td>
        </tr>
        <tr>
          <th scope="row"><%= User.human_attribute_name(:role) %></th>
          <td><%= @user.role_i18n %></td>
        </tr>
        <tr>
          <th scope="row"><%= User.human_attribute_name(:name) %></th>
          <td><%= @user.name %></td>
        </tr>
        <tr>
          <th scope="row"><%= User.human_attribute_name(:email) %></th>
          <td><%= @user.email %></td>
        </tr>
        <tr>
          <th scope="row"><%= User.human_attribute_name(:created_at) %></th>
          <td><%= l @user.created_at, format: :long %></td>
        </tr>
        <tr>
          <th scope="row"><%= User.human_attribute_name(:uid) %></th>
        <% if @user.uid.present?%>
          <td>LINEに連携済み</td>
       <% else %>
          <td>LINEに連携していません</td>
        <% end %>
        </tr>
      </table>
    </div>
  </div>
</div>