config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'static_pages#top'
  get '/index.html', to: 'static_pages#top'
  get '/privacy_policy', to: 'static_pages#privacy_policy'
  get '/term_of_use', to: 'static_pages#term_of_use'
  get '/guide', to: 'static_pages#guide'
  get :sign_up, to: 'users#new'
  post :sign_up, to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  post '/guest_login', to: 'guest_sessions#create'
  delete '/guest_logout', to: 'guest_sessions#destroy'
  post '/callback', to: 'line_bot#callback'
  get '/callback', to: 'oauths#callback'
  post 'oauth/callback', to: 'oauths#callback'
  get 'oauth/:provider', to: 'oauths#oauth', as: :auth_at_provider
  resources :items do
    collection do
      get 'search'
      get 'already_expired'
    end
    patch 'increment', on: :member
    patch 'decrement', on: :member
  end
  resources :users, only: %i[new create destroy]
  resource :authentication
  resource :profile, only: %i[show edit update]
  resources :shopping_lists, only: %i[index create new edit update]
  delete 'shopping_lists/destroy', to: 'shopping_lists#destroy_selected', as: :destroy_selected_shopping_lists
  resources :password_resets, only: %i[new create edit update]
  resources :inquiries, only: %i[new create] do
    get '/mentions', to: 'inquiries#mentions'
  end

  namespace :admin do
    root to: 'dashboards#index'
    get '/login', to: 'user_sessions#new'
    post '/login', to: 'user_sessions#create'
    delete '/logout', to: 'user_sessions#destroy'
    resources :users, only: %i[index edit update show destroy] do
      collection do
        get 'search'
      end
    end

    resources :items, only: %i[index edit update show destroy] do
      collection do
        get 'search'
      end
    end

    resources :shopping_lists, only: %i[index update show destroy] do
      collection do
        get 'search'
      end
    end
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/shopping_list.rb
class ShoppingList < ApplicationRecord
  belongs_to :user
  with_options presence: true do 
    validates :product
    validates :number
  end
  validates :trait, length: { minimum: 0, maximum: 30 }

  scope :search_product, ->(product) { where("product LIKE :word", word: "%#{product}%") }
  scope :search_trait, ->(trait) { where("trait LIKE :word", word: "%#{trait}%") }
  scope :search_user_email, ->(user_email) { joins(:user).where("users.email LIKE ?", "%#{user_email}%") }
end

app/controllers/admin/shopping_lists_controller.rb
class Admin::ShoppingListsController < Admin::BaseController
  before_action :set_shopping, only: %i[edit show destroy]

  def index
    @shopping_lists = ShoppingList.all.order(created_at: :desc).page(params[:page])
  end

  def edit; end

  def show; end

  def destroy
    @shopping_list.destroy!
    redirect_to admin_shopping_lists_path, success: t('.success')
  end

  def search
    @search_shopping_lists_form = SearchShoppingListsForm.new(search_shopping_list_params)
    @search_shopping_lists = @search_shopping_lists_form.search.order(created_at: :desc).page(params[:page]).per(20)
  end

  private

  def set_shopping
    @shopping_list = ShoppingList.find(params[:id])
  end

  def shopping_list_params
    params.require(:shopping_list).permit(:product, :number, :trait, :user_email)
  end

  def search_shopping_list_params
    params.fetch(:q, {}).permit(:title, :detail, :user_email)
  end
end

app/controllers/shopping_lists_controller.rb
class ShoppingListsController < ApplicationController
  before_action :set_shopping, only: %i[edit update]
  def index
    @shopping_lists = ShoppingList.where(user_id: current_user.id)
  end

  def new
    @shopping_list = ShoppingListCollectionForm.new
  end

  def create
    @shopping_list = ShoppingListCollectionForm.new(shopping_list_collection_params)
    if @shopping_list.save
      redirect_to shopping_lists_path, success: t('.success')
    else
      flash.now[:danger] = t('.fail')
      render :new
    end
  end

  def edit; end

  def update
    if @shopping_list.update(shopping_list_params)
      redirect_to shopping_lists_path, success: t('.success')
    else
      render :edit, danger: t('not_to_update')
    end
  end

  def destroy; end

  def destroy_selected
    selected_shopping_list_ids = params[:selected_shopping_lists]

    if selected_shopping_list_ids.present?
      ShoppingList.where(id: selected_shopping_list_ids).destroy_all
      flash[:success] = t('.success')
    else
      flash[:warning] = t('.no_selection')
    end
    redirect_to shopping_lists_path
  end

  private

  def set_shopping
    @shopping_list = ShoppingList.find(params[:id])
  end

  def shopping_list_params
    params.require(:shopping_list).permit(:product, :number, :trait)
  end

  def shopping_list_collection_params
    params.require(:shopping_list_collection_form)
    .permit(shopping_lists_attributes: [:product, :number, :trait]).merge(user_id: @current_user.id)
  end
end

app/views/admin/shopping_lists/_search_forms_shopping_lists.erb
<%= form_with model: @search_shopping_lists_form, scope: :q, url: search_admin_shopping_lists_path, method: :get, local: true do |f| %>
  <div class="mb-3">
    <%= f.text_field :product, placeholder: '商品名' %>
    <%= f.text_field :trait, placeholder: '概要' %>
    <%= f.search_field :user_email, placeholder: 'メールアドレス'%>
    <%= f.submit '検索', class: 'btn btn-outline-primary' %>
  </div>
<% end %>

app/views/admin/shopping_lists/_shopping_list.html.erb
<tr>
  <td>
    <%= shopping_list.id %>
  </td>
  <td>
    <%= link_to shopping_list.product %>
  </td>
  <td>
    <%= shopping_list.number %>
  </td>
  <td>
    <%= shopping_list.trait %>
  </td>
  <td>
    <%= shopping_list.user.email %>
  </td>
  <td>
    <%= l shopping_list.created_at, format: :long %>
  </td>
  <td>
    <%= link_to t('defaults.delete'), admin_shopping_list_path(shopping_list), method: :delete, data: { confirm: t('defaults.message.deleted_comfirm') }, class: 'btn btn-danger' %>
  </td>
</tr>

app/views/admin/shopping_lists/index.html.erb
<% content_for(:title, t('.title')) %>
<div class="container mb-5 pt-2">
  <h1><%= t('.title') %></h1>
  <div class="row">
    <div class="col-md-12 mb-3">
     <%= render 'search_forms_shopping_lists' %>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12">
      <table class="table table-striped">
        <thead>
        <tr>
          <th scope="col"><%= ShoppingList.human_attribute_name(:id) %></th>
          <th scope="col"><%= ShoppingList.human_attribute_name(:product) %></th>
          <th scope="col"><%= ShoppingList.human_attribute_name(:number) %></th>
          <th scope="col"><%= ShoppingList.human_attribute_name(:trait) %></th>
           <th scope="col"><%= ShoppingList.human_attribute_name(:email) %></th>
          <th scope="col"><%= ShoppingList.human_attribute_name(:created_at) %></th>
        </tr>
        </thead>
        <tbody>
        <%= render @shopping_lists %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12">
      <!-- ページネーション -->
      <%= paginate @shopping_lists %>
    </div>
  </div>
</div>

app/views/admin/shopping_lists/search.html.erb
<% content_for(:title, t('.title')) %>
<div class="container mb-5 pt-2">
  <h1><%= t('.title') %></h1>
  <div class="row">
    <div class="col-md-12 mb-3">
      <%= render 'search_forms_shopping_lists' %>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12">
      <table class="table table-striped">
        <thead>
        <tr>
          <th scope="col"><%= ShoppingList.human_attribute_name(:id) %></th>
          <th scope="col"><%= ShoppingList.human_attribute_name(:product) %></th>
          <th scope="col"><%= ShoppingList.human_attribute_name(:number) %></th>
          <th scope="col"><%= ShoppingList.human_attribute_name(:trait) %></th>
          <th scope="col"><%= ShoppingList.human_attribute_name(:email) %></th>
          <th scope="col"><%= ShoppingList.human_attribute_name(:created_at) %></th>
        </tr>
        </thead>
        <tbody>
        <%= render @search_shopping_lists %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12">
      <!-- ページネーション -->
      <%= paginate @search_shopping_lists %>
    </div>
  </div>
</div>